# This needs to be run from repository's root


FROM node:18.16.1-alpine as compile

# create build dirs
RUN mkdir -p /app/build
WORKDIR /app/build

# copy sources and compile front
COPY front .
RUN npm install
RUN npx ng build --configuration=production 

# change base image to embed only nginx and front files in resulting docker image
FROM nginx:1.21.3 as RUN

# copy our nginx configuration to container
COPY nginx.conf /etc/nginx

# copy compiled files from previous step
WORKDIR /usr/share/nginx/html
COPY --from=compile /app/build/dist/front/* ./

